services:
  db:
    image: mariadb:10.11
    container_name: team-mariadb
    ports:
      - "3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "0000"
      MARIADB_DATABASE: music_space_db
      MARIADB_AUTO_UPGRADE: "yes"
    restart: always

  redis:
    image: redis:latest
    container_name: team-redis
    ports:
      - "6379:6379"
    restart: always